import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import connectDB from './config/db.js';
import globalErrorHandler from './middlewares/errorMiddleware.js';
import AppError from './utils/AppError.js';
import letterRoutes from './routes/letterRoutes.js';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const app = express();
connectDB();

const allowedOrigins = (process.env.CORS_ORIGIN || 'http://localhost:3000,http://localhost:5173')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean);

app.use('/api', cors({
  origin(origin, callback) {
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
      return;
    }

    callback(new AppError('Not allowed by CORS', 403));
  },
  credentials: true,
}));

// Base64 adds roughly 33% to attachment size. This accommodates the validated
// 15 MB attachment limit plus the rest of the JSON payload.
app.use(express.json({ limit: '25mb' }));

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.use('/api/letter', letterRoutes);

// --- Serve the built client (production) ---
// Generated by `npm --prefix client run build` (Vite + prerender) into client/dist.
const clientDist = path.resolve(__dirname, '../client/dist');

if (fs.existsSync(clientDist)) {
  // Real files only: hashed JS/CSS, images, sitemap.xml, robots.txt.
  app.use(express.static(clientDist, { index: false, redirect: false }));

  // Any other (non-API) GET -> the prerendered HTML for that exact route,
  // falling back to the SPA shell for client-only / unknown routes.
  app.get('*', (req, res, next) => {
    if (req.path.startsWith('/api')) return next();
    const rel = path.normalize(req.path).replace(/^(\.\.[\\/])+/, '');
    const prerendered = path.join(clientDist, rel, 'index.html');
    const shell = path.join(clientDist, 'index.html');
    res.sendFile(fs.existsSync(prerendered) ? prerendered : shell);
  });
} else {
  app.get('/', (req, res) => {
    res.json({ status: 'ok' });
  });
}

app.all('*', (req, res, next) => {
  next(new AppError(`Can't find ${req.originalUrl} on this server!`, 404));
});

app.use(globalErrorHandler);

const PORT = process.env.PORT || process.env.SERVER_PORT || 5000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
